/**
 * Aquí van las constantes que identifican los tipos de acción
 */
export const SAMPLE_ACTION = "SAMPLE_ACTION"
export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS'
export const GET_USER_BY_ID = 'GET_USER_BY_ID'
export const GET_PROJECT_BY_ID = 'GET_PROJECT_BY_ID'
export const POST_PROJECT = 'POST_PROJECT'
export const SERVER_MESSAGE = 'SERVER_MESSAGE'
export const RESET_USER_BY_ID = 'RESET_USER_BY_ID'
export const RESET_PROJECT_BY_ID = 'RESET_PROJECT_BY_ID'
export const ORDER_PROJECTS_BY = 'ORDER_PROJECTS_BY'
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const ADMIN_SUSPEND_USER = 'ADMIN_SUSPEND_USER'
export const ADMIN_SUSPEND_PROJECT = 'ADMIN_SUSPEND_PROJECT'
export const LOGGED_USER_ID = 'LOGGED_USER_ID'
export const GET_CONTRUBUTION = 'GET_CONTRUBUTION'
export const LIST_PAYMENTS = 'LIST_PAYMENTS'
export const POST_REVIEW = 'POST_REVIEW'
export const GET_REVIEWS = "GET_REVIEWS"
export const GET_REPORTS_PROJECTS = 'GET_REPORTS_PROJECTS'
export const GET_REPORTS_USERS = 'GET_REPORTS_USERS'
export const POST_REPORT_USER ='POST_REPORT_USER'
export const POST_REPORT_PROJECT ='POST_REPORT_PROJECT'
