export const technologies = [
    { name: "Java" },
    { name: "C#" },
    { name: "C++" },
    { name: "Javascript" },
    { name: "ReactJs" },
    { name: "ReactNative" },
    { name: "NodeJs" },
    { name: "ExpressJs" },
    { name: "NextJs" },
    { name: "HTML" },
    { name: "CSS" },
    { name: "Less" },
    { name: "Sass" },
    { name: "Kotlin" },
    { name: "Swift" },
    { name: "PHP" },
    { name: "Python" },
    { name: "Ruby on rails" },
    { name: "SQL" },
    { name: "PostreSQL" },
    { name: "MySQL" },
    { name: "Redux" },
    { name: "TypeScript" },
    { name: "Cobol" },
    { name: "Spring Boot" },
    { name: ".NET" },
    { name: "Django" },
    { name: "MongoDb" },
    { name: "Sequelize" },
    { name: "Vue" },
    { name: "Angular" },
    { name: "Flask" },
    { name: "Flutter" },
    { name: "Xamarin" },
    { name: "Asp.Net" },
    { name: "JQuery" },
    { name: "VisualBasic" },
    { name: "Bootstrap" },
    { name: "Tailwind" },
    { name: "Bulma" },
    { name: "Objetive-C" },
    { name: "Laravel" },
    { name: "Symfony" },
    { name: "Golang" },
    { name: "Wordpress" },
    { name: "C" },
    { name: "Docker" },
    { name: "GraphQL" },
    { name: "Jest" },
    { name: "Heroku" },
    { name: "Amazon Web Services" }
];